@startuml
!theme cerulean
'https://plantuml.com/sequence-diagram

autonumber
skinparam maxMessageSize 70
participant Terminal
participant "Main Program\n(in app.rb)"
participant "BookRepository\n(in lib/book_repository.rb)"
participant "DatabaseConnection class\n(in lib/database_connection.rb)"
participant "Postgres\nDatabase"
"Terminal" -> "Main Program\n(in app.rb)": Runs `ruby app.rb`
"Main Program\n(in app.rb)" -> "Terminal": Authentication Response :"Opens connection to database calling method `connect` on DatabaseConnection"
"Opens connection to database calling method `connect` on DatabaseConnection" -> "DatabaseConnection class\n(in lib/database_connection.rb)"

@enduml